packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': ^24.1.0
  "@trpc/client": 11.3.1
  "@trpc/react-query": 11.3.1
  "@trpc/server": 11.3.1
  drizzle-orm: ^0.44.3
  tsx: ^4.20.3
  typescript: ^5.9.2
  vitest: ^3.2.4

catalogMode: manual

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
