packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': ^2.2.7
  '@libsql/client': ^0.15.10
  '@trpc/client': ^11.6.0
  '@trpc/react-query': ^11.6.0
  '@trpc/server': ^11.6.0
  '@trpc/tanstack-react-query': ^11.6.0
  '@types/colorthief': ^2.6.0
  '@types/hast': ^3.0.4
  '@types/json-schema': ^7.0.15
  '@types/node': ^24.8.1
  '@typescript/native-preview': 7.0.0-dev.20251023.1
  colorthief: ^2.6.0
  drizzle-kit: beta
  drizzle-orm: 1.0.0-beta.1-ac4ce44
  hast-util-sanitize: ^5.0.2
  json-schema: ^0.4.0
  rehype-raw: ^7.0.0
  rehype-sanitize: ^6.0.0
  remark-gfm: ^4.0.1
  sharp: ^0.34.3
  superjson: ^2.2.2
  trpc-to-openapi: ^3.1.0
  tsx: ^4.20.3
  typescript: ^5.9.3
  unified: ^11.0.5
  unist-util-visit: ^5.0.0
  vitest: ^4.0.2
  zod: ^4.1.12
  zod-openapi: ^5.4.3

catalogMode: strict

disallowWorkspaceCycles: true

minimumReleaseAge: 2880

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - onnxruntime-node
  - sharp
