packages:
  - apps/*
  - packages/*

catalog:
  '@trpc/client': 11.3.1
  '@trpc/react-query': 11.3.1
  '@trpc/server': 11.3.1
  '@types/node': ^24.1.0
  drizzle-orm: ^0.44.3
  sharp: ^0.34.3
  trpc-to-openapi: ^2.3.2
  tsx: ^4.20.3
  typescript: ^5.9.2
  vitest: ^3.2.4
  zod: 3.25.76

catalogMode: manual

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
