packages:
  - apps/*
  - packages/*

catalog:
  '@codemirror/commands': ^6.9.0
  '@codemirror/lang-json': ^6.0.2
  '@codemirror/lint': ^6.9.0
  '@codemirror/view': ^6.38.6
  '@fastify/deepmerge': ^3.1.0
  '@libsql/client': ^0.15.10
  '@trpc/client': ^11.6.0
  '@trpc/react-query': ^11.6.0
  '@trpc/server': ^11.6.0
  '@trpc/tanstack-react-query': ^11.6.0
  '@types/json-schema': ^7.0.15
  '@types/node': ^24.8.1
  '@typescript/native-preview': ^7.0.0-dev.20251018.1
  '@uiw/codemirror-extensions-events': ^4.25.2
  '@uiw/codemirror-theme-vscode': ^4.25.2
  '@uiw/react-codemirror': ^4.25.2
  codemirror-json-schema: ^0.8.1
  drizzle-kit: beta
  drizzle-orm: 1.0.0-beta.1-ac4ce44
  json-schema: ^0.4.0
  sharp: ^0.34.3
  superjson: ^2.2.2
  trpc-to-openapi: ^3.1.0
  tsx: ^4.20.3
  typescript: ^5.9.3
  vitest: ^3.2.4
  zod: ^4.1.12
  zod-openapi: ^5.4.3

catalogMode: strict

disallowWorkspaceCycles: true

minimumReleaseAge: 2880

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - onnxruntime-node
  - sharp
