packages:
  - apps/*
  - packages/*

catalog:
  '@trpc/client': 11.3.1
  '@trpc/react-query': 11.3.1
  '@trpc/server': 11.3.1
  '@types/node': ^24.1.0
  drizzle-kit: beta
  drizzle-orm: 1.0.0-beta.1-40d80bd
  sharp: ^0.34.3
  superjson: ^2.2.2
  trpc-to-openapi: ^3.0.0
  tsx: ^4.20.3
  typescript: ^5.9.2
  vitest: ^3.2.4
  zod: ^4.0.17
  zod-openapi: ^5.0.1

catalogMode: manual

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - onnxruntime-node
  - sharp
  - trpc-ui
