packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': ^2.3.2
  '@libsql/client': ^0.15.10
  '@trpc/client': ^11.7.1
  '@trpc/react-query': ^11.7.1
  '@trpc/server': ^11.7.1
  '@trpc/tanstack-react-query': ^11.7.1
  '@types/json-schema': ^7.0.15
  '@types/node': ^24.9.2
  '@typescript-eslint/parser': ^8.46.2
  '@typescript/native-preview': 7.0.0-dev.20251023.1
  chevrotain: ^11.0.3
  drizzle-kit: beta
  drizzle-orm: 1.0.0-beta.1-ac4ce44
  elkjs: ^0.11.0
  json-schema: ^0.4.0
  reactflow: ^11.11.4
  sharp: ^0.34.3
  superjson: ^2.2.5
  trpc-to-openapi: ^3.1.0
  tsx: ^4.20.3
  typescript: ^5.9.3
  vitest: ^3.2.4
  zod: ^4.1.12
  zod-openapi: ^5.4.3

catalogMode: strict

disallowWorkspaceCycles: true

minimumReleaseAge: 2880

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - onnxruntime-node
  - sharp
